name = "Spell Dimension"
author = "Karashok Leo"
version = "0.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d0da85083b5e57b4a7b2d8e51e211f6fce07c368f529962fba31139f189bd7b"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
