name = "Spell Dimension"
author = "Karashok Leo"
version = "0.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fb1b3f8839c249f42050b2095406895f417c3bdeb2961b12c4cf5d777d7e115"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
