name = "Spell Dimension"
author = "Karashok Leo"
version = "0.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c52ac2d6b1a56ae3821fa41f9fc1954a3ba1155014065d6818c85ebdb412160"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
