MobGriefing:
  Disable_Enderman_Pick_Up: false
  Disable_Creeper_Griefing: false
  Disable_Ghast_Griefing: false
  Disable_Zombie_Break_Door: false
GameRule:
  Disable_Nether_Portal_Spawning_Zombified_Piglin: false
  Disable_Bat_Spawning: false
  Disable_Ghast_Spawning_Above_Bedrock: false
  Disable_Trample: false
  Drop_Player_Head: true
  Fast_Budding_Amethyst: true
  Superb_Medical_Skill: false
BetterSpawner:
  Enable: false
  Player_Range: 16
  Max_Nearby: 6
  Min_Delay: 200
  Max_Delay: 800
  Spawner_Range: 8
  Spawner_Height: 3
  Spawner_Count: 4
  Disable_Light_Restriction: false
  Disable_Fluid_Restriction: false
CommandReg:
  Command_Tick: false
Enchantment:
  Disable_Enchantments_Conflict: true
  Real_Infinity: true
  Better_Crossbow: true
  Never_Expensive: true
  Better_Mending: true
StackableItem:
  Potions: 16
  Snowball: 64
  Bed: 16
LootTable:
  Always_Drop_Blaze_Rod: false
  Wither_Skeleton_Drop_Skull: false
  Mineable_Budding_Amethyst: true
MobActivity:
  Disable_Piglin_Zombify: true
  Creeper_Attack_Snow_Golem: false
Recipes:
  Enchanted_Golden_Apple: false
  Budding_Amethyst: true
