name: Modpack export

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download source code
      uses: actions/checkout@v6

    - name: Download packwiz
      run: |
        curl.exe --fail --location --retry 3 --output "packwiz.exe" "https://github.com/packwiz/packwiz/releases/latest/download/packwiz-windows-x86_64.exe"
        if (-not (Test-Path "packwiz.exe")) { throw "packwiz.exe was not downloaded" }

    - name: Export modpack
      run: |
        .\packwiz.exe cf export --output client.zip
        .\packwiz.exe cf export --side server --output server.zip

    - name: Upload modpack (client)
      uses: actions/upload-artifact@v4
      with:
        name: modpack-client
        path: "client.zip"
    - name: Upload modpack (server)
      uses: actions/upload-artifact@v4
      with:
        name: modpack-server
        path: "server.zip"
